resolver: lts-24.29
compiler: ghc-9.14.1

compiler-check: match-exact

packages:
    - .

allow-newer: true

flags:
    haskell-in-depth:
        with-pg: True

extra-deps:
    - Chart-1.9.5
    - Chart-diagrams-1.9.5.1
    - streaming-utils-0.2.5.0
    - HDBC-postgresql-2.4.0.0
